### ISSUE TITLE
构建本地镜像，并通过docker-compse启动

### ISSUE THREAD

**Issue by zolagz** [zfb132/frp_info#5]
拉取代码，并在目录下执行：

sudo docker build -t whuzfb/frp_info:latest  .

然后新建 docker-compose.yml文件

```
version: '3'
services:
  frp_info:
    image: whuzfb/frp_info:latest
    restart: always
    volumes:
      - ./data/config.py:/frp/app/config.py
      - ./data/allow.txt:/frp/allow.txt
    ports:
      - "6666:6666"
```

然后启动

sudo docker-compose up -d
